
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      docker_image_name:
        description: 'Name of the Docker image to deploy'
        required: true
        default: 'avant-garble'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - name: 'Authenticate with Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        create_credentials_file: true
        # token_format: 'access_token'
        # project_id: ${{ secrets.GCP_PROJECT_ID }}
        workload_identity_provider: ${{ secrets.WIF_PROVIDER  }}
        service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

    - name: Configure Docker
      run: |
        gcloud auth configure-docker

    - name: Build Docker Image
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest .
    
    - name: Push Docker Image
      run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy avant-garble \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest \
          --platform managed \
          --region europe-west2 \
          --allow-unauthenticated \
          --set-env-vars BSKY_USERNAME=${{ secrets.BSKY_USERNAME }},BSKY_PASSWORD=${{ secrets.BSKY_PASSWORD }}
